Repository ProjectCoco/wayfarer-frontend, pull requests merged in 2022-12, with the labels that each got.

#9 feat : 회원가입 모달창 레이아웃 완료
  components/SignIn/SignInDialog.tsx
  components/common/Input/Asterisk.tsx
  components/common/Input/CheckBox.tsx
  components/modal/Complete/CompleteDialog.tsx
  components/modal/ModalButton.tsx
  components/modal/SignIn/ButtonBox.tsx
  components/modal/SignIn/DialogHeader.tsx
  components/modal/SignIn/SignInDialog.tsx
  components/modal/SignIn/SocialButton.tsx
  components/modal/SignUp/DropDownInput.tsx
  components/modal/SignUp/LabelCheck.tsx
  components/modal/SignUp/LabelInput.tsx
  components/modal/SignUp/ModalInput.tsx
  components/modal/SignUp/SignUpDialog.tsx
  components/pages/write/Label.tsx
  components/pages/write/LabelBlock.tsx
  components/pages/write/TagInput.tsx
  components/pages/write/TextArea.tsx
  components/pages/write/WriteForm.tsx
  components/pages/write/WriteInput.tsx
  context/DialogContext.tsx
  hooks/Signup/useChecked.tsx
  hooks/Signup/useSignUpForm.tsx
  hooks/Write/useHandleTag.tsx
  pages/write/index.tsx
  public/common/Glossy.png
  public/common/btn_arrow.svg
  public/common/btn_dropdown.svg
Labels: feature

#10 [FE] BigCards 컴포넌트, SubBanner 컴포넌트 완료
  components/common/Banner/Banner.tsx
  components/common/Banner/BannerButton.tsx
  components/common/Banner/SubBanner.tsx
  components/common/Header/Header.tsx
  components/pages/Home/BigCard.tsx
  components/pages/Home/BigCardHover.tsx
  components/pages/Home/BigCards.tsx
  components/pages/Home/CardsHeader.tsx
  components/pages/Home/LikeButton.tsx
  pages/index.tsx
  public/Banner/SubBanner.svg
  public/Cards/BigCards/BigStudyCardDev.svg
  public/Cards/BigCards/Like.svg
Labels: feature, design

#12 [FE] Footer component 추가
  components/common/Footer/Footer.tsx
  components/pages/Home/BigCardCarousel.tsx
  pages/_app.tsx
  public/Footer/facebook.svg
  public/Footer/index.ts
  public/Footer/instagram.svg
  public/Footer/youtube.svg
  public/Logo/FooterLogo.svg
Labels: feature, design

#13 Feat : 글쓰기 페이지 레이아웃 1차 완성
  components/modal/Complete/CompleteDialog.tsx
  components/pages/write/DropDown.tsx
  components/pages/write/DropDownIcon.tsx
  components/pages/write/DropDownList.tsx
  components/pages/write/SubmitButton.tsx
  components/pages/write/TagInput.tsx
  components/pages/write/TextArea.tsx
  components/pages/write/WriteForm.tsx
  components/pages/write/WriteInput.tsx
  hooks/Write/useDropDown.tsx
  hooks/Write/useForm.tsx
  pages/write/index.tsx
  utils/writeMenu/index.ts
Labels: documentation, feature

#15 feat: community 페이지 추가 및 레이아웃, CommunityPostDetailModal 추가 등
  components/common/Cards/SmallCardHover.tsx
  components/common/Header/Header.tsx
  components/pages/Community/AuthorOccupationTag.tsx
  components/pages/Community/CommunityCard.tsx
  components/pages/Community/CommunityCardCarousel.tsx
  components/pages/Community/CommunityCards.tsx
  components/pages/Community/CommunityInput.tsx
  components/pages/Community/CommunityModal/CommunityPostComment.tsx
  components/pages/Community/CommunityModal/CommunityPostDetailModal.tsx
  components/pages/Community/CommunityModal/PostLikeButton.tsx
  components/pages/Community/CommunityPosts.tsx
  components/pages/Community/CommunityTag.tsx
  components/pages/Community/CommuntiyPost.tsx
  components/pages/Community/MessageCircle.tsx
  components/pages/Community/PostSortFilter.tsx
  components/pages/Community/ThumbsUp.tsx
  components/pages/Home/BigCardCarousel.tsx
  components/pages/Project/TechStackFilter.tsx
  hooks/Carousel/useSlide.tsx
  hooks/FilterTag/useTagClick.tsx
  hooks/Header/useMenuSelect.tsx
  pages/community/index.tsx
  public/Community/Close.svg
  public/Community/Enter.svg
  public/Community/MessageCircle.svg
  public/Community/Pencil.svg
  public/Community/ThumbsUp.svg
  public/Community/UpDownArrow.svg
Labels: bug, feature, refactor
