Repository ProjectCoco/wayfarer-frontend, pull requests merged in 2022-11, with the labels that each got.

#5 Feat : 회원가입 모달 및 컨텍스트 추가
  components/SignIn/ButtonBox.tsx
  components/SignIn/DialogHeader.tsx
  components/SignIn/SignInDialog.tsx
  components/SignIn/SocialButton.tsx
  components/modal/Modal.tsx
  components/modal/OverLay.tsx
  context/DialogContext.tsx
  public/common/ico_close.svg
  public/social/google.svg
  public/social/kakao.svg
  public/social/naver.svg
Labels: enhancement

#6 design: 메인, 스터디 페이지 레이아웃 설정 및 헤더 디자인 변경
  components/common/Banner.tsx
  components/common/Header.tsx
  components/pages/Home/TitleAndSubTitle.tsx
  pages/index.tsx
  pages/study/index.tsx
  public/Banner/MainBanner.svg
  public/Logo/Logo.svg
  styles/DefaultTheme.ts
  styles/GlobalStyle.ts
  styles/styled.d.ts
Labels: enhancement

#7 feat: Banner 폴더 생성 및 BannerButton 컴포넌트 생성
  components/common/Banner.tsx
  components/common/Banner/Banner.tsx
  components/common/Banner/BannerButton.tsx
  pages/index.tsx
  pages/study/index.tsx
Labels: feature

#8 refactor: Header 컴포넌트 역할 분리를 위한 코드 리팩토링
  components/common/Header/Header.tsx
  hooks/Header/useHeaderScroll.tsx
  hooks/Header/useMenuSelect.tsx
  pages/_app.tsx
Labels: refactor
